import type { Metadata } from 'next';
import './globals.css';
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import SessisonProvider from "@/components/SessisonProvider";
import Navbar from "@/components/nav/Navbar";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="ja" suppressHydrationWarning>
        <body className={cn("antialiased dark:bg-[#09090B]")}>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <main className="max-w-7xl mx-auto lg:py-10 space-y-10 p-5 lg:p-0">
              <Navbar />
              {children}
            </main>
          </ThemeProvider>
          <Toaster />
          <SessisonProvider />
        </body>
      </html>
    </>
  )}
